// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// 在 Cloudflare Pages / D1 场景下，其实不会通过 DATABASE_URL 直连数据库，
// 这里只是为了让 Prisma 在构建时能正常生成 Client。
// 如果没有设置 DATABASE_URL，则回退到本地 sqlite 文件，保证 `prisma generate` 不会报错。
const databaseUrl =
  process.env.DATABASE_URL ?? "file:./dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
